apiVersion: apps/v1
kind: Deployment
metadata:
  name: jw-library-read-api
  namespace: default
  labels:
    app: jw-library-read-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jw-library-read-api
  template:
    metadata:
      labels:
        app: jw-library-read-api
    spec:
      containers:
        - name: jw-library-read-api
          image: brunomassaini/jw-library-read-api:latest
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: jw-library-read-api-config
          volumeMounts:
            - name: read-status-storage
              mountPath: /app/data
          readinessProbe:
            httpGet:
              path: /openapi.json
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /openapi.json
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: read-status-storage
          persistentVolumeClaim:
            claimName: jw-library-read-api-data
