apiVersion: v1
kind: Service
metadata:
  name: jw-library-read-api
  namespace: default
  labels:
    app: jw-library-read-api
spec:
  selector:
    app: jw-library-read-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
